/**
 * Links — 36 checks.
 * Internal links, backlinks, anchors, rel attributes and link targets.
 */
import { pageCheck, type PageCheck } from './types.ts';
import { normalizeUrl, isNonDescriptiveAnchor, type PageData } from '../extract.ts';
import type { SiteData as Site } from './types.ts';

export const LINK_LIMITS = {
  maxInternalLinks: 100,
  maxExternalLinks: 100,
  externalLinkNotice: 10,
  maxIdenticalInternal: 100,
  maxLinksBeforeH1: 100,
  minInternalBacklinks: 10,
  maxSameAnchorToSamePage: 2,
};

const K = LINK_LIMITS;

const followedInternal = (p: PageData) => p.links.filter((l) => l.isInternal && !l.nofollow && !l.isFragmentOnly);
const inboundOf = (p: PageData, site: Site) => site.inbound.get(normalizeUrl(p.finalUrl)) ?? [];

const targetStatus = (site: Site, href: string | null): number | null => {
  if (!href) return null;
  return site.byUrl.get(normalizeUrl(href))?.status ?? null;
};

// ---------------------------------------------------------------------------

const outgoingChecks: PageCheck[] = [
  pageCheck({
    id: 'page-has-no-outgoing-links', title: 'Page has no outgoing links',
    category: 'links', severity: 'critical',
    why: 'A page with no outgoing links is a dead end for crawlers and traps link equity. It is almost always a rendering failure rather than a design choice.',
    fix: 'Add contextual internal links. If navigation is client-rendered, ensure real <a href> elements exist in the server HTML.',
    test: (p) => p.links.filter((l) => l.href).length === 0,
  }),
  pageCheck({
    id: 'only-one-followed-internal-link', title: 'Has only one followed internal linking URL',
    category: 'links', severity: 'warning',
    why: 'A single followed internal link severely limits how link equity flows onward and suggests the page sits outside the site structure.',
    fix: 'Add contextual links to related pages.',
    test: (p) => {
      const n = new Set(followedInternal(p).map((l) => normalizeUrl(l.href!))).size;
      return n === 1 ? '1 followed internal link' : false;
    },
  }),
  pageCheck({
    id: 'more-than-100-internal-links', title: 'Page has more than 100 internal links',
    category: 'links', severity: 'warning',
    why: 'Very high link counts dilute the equity passed to each target and make crawling less efficient.',
    fix: 'Reduce navigation and footer link volume, or paginate large listings.',
    test: (p) => {
      const n = p.links.filter((l) => l.isInternal).length;
      return n > K.maxInternalLinks ? n + ' internal links' : false;
    },
  }),
  pageCheck({
    id: 'more-than-100-external-links', title: 'Page has more than 100 external links',
    category: 'links', severity: 'warning',
    why: 'Excessive outbound linking leaks equity and can look like a link farm.',
    fix: 'Review whether all outbound links are necessary; add rel=nofollow where appropriate.',
    test: (p) => {
      const n = p.links.filter((l) => l.isExternal).length;
      return n > K.maxExternalLinks ? n + ' external links' : false;
    },
  }),
  pageCheck({
    id: 'more-than-10-external-links', title: 'Page has more than 10 external links',
    category: 'links', severity: 'notice',
    why: 'A high outbound count relative to page size is worth reviewing, though not inherently harmful.',
    fix: 'Confirm each outbound link serves the reader.',
    test: (p) => {
      const n = p.links.filter((l) => l.isExternal).length;
      return n > K.externalLinkNotice ? n + ' external links' : false;
    },
  }),
  pageCheck({
    id: 'more-than-100-identical-internal-links', title: 'Page has more than 100 identical internal links',
    category: 'links', severity: 'warning',
    why: 'Repeating the same destination many times wastes crawl budget and adds no ranking value beyond the first occurrence.',
    fix: 'Consolidate repeated links, usually generated by a listing template.',
    test: (p) => {
      const counts = new Map<string, number>();
      for (const l of p.links) {
        if (!l.isInternal || !l.href) continue;
        const k = normalizeUrl(l.href);
        counts.set(k, (counts.get(k) ?? 0) + 1);
      }
      const worst = [...counts.entries()].sort((a, b) => b[1] - a[1])[0];
      return worst && worst[1] > K.maxIdenticalInternal ? worst[1] + '× to ' + worst[0] : false;
    },
  }),
  pageCheck({
    id: 'more-than-2-links-same-anchor', title: 'Page has more than 2 links to internal page with the same anchor',
    category: 'links', severity: 'notice',
    why: 'Repeating an identical anchor to the same destination adds no incremental signal and can read as over-optimisation.',
    fix: 'Vary anchor text or reduce duplicate links.',
    test: (p) => {
      const counts = new Map<string, number>();
      for (const l of p.links) {
        if (!l.isInternal || !l.href || !l.anchor) continue;
        const k = normalizeUrl(l.href) + '|' + l.anchor.toLowerCase();
        counts.set(k, (counts.get(k) ?? 0) + 1);
      }
      const worst = [...counts.entries()].sort((a, b) => b[1] - a[1])[0];
      return worst && worst[1] > K.maxSameAnchorToSamePage
        ? worst[1] + '× "' + worst[0].split('|')[1] + '"' : false;
    },
  }),
  pageCheck({
    id: 'more-than-100-links-before-h1', title: 'Page has more than 100 links before H1 tag',
    category: 'links', severity: 'notice',
    why: 'A large navigation block ahead of the main heading pushes primary content down the DOM, which weakens its prominence.',
    fix: 'Simplify the header, or move navigation after the main content in source order and reposition with CSS.',
    test: (p) => {
      const n = p.links.filter((l) => l.beforeH1).length;
      return n > K.maxLinksBeforeH1 ? n + ' links before H1' : false;
    },
  }),
  pageCheck({
    id: 'nofollow-outgoing-internal-links', title: 'Page has nofollow outgoing internal links',
    category: 'links', severity: 'warning',
    why: 'Nofollow on internal links blocks equity flow within your own site. PageRank sculpting has not worked since 2009 — the equity is discarded, not redirected.',
    fix: 'Remove rel=nofollow from internal links.',
    test: (p) => {
      const n = p.links.filter((l) => l.isInternal && l.nofollow).length;
      return n ? n + ' nofollow internal link(s)' : false;
    },
  }),
  pageCheck({
    id: 'footer-links-nofollow', title: 'Links in the footer with a no-follow attribute',
    category: 'links', severity: 'opportunity',
    why: 'Nofollowed footer links to your own pages discard equity that would otherwise reach them.',
    fix: 'Remove nofollow from internal footer links.',
    test: (p) => {
      const n = p.links.filter((l) => l.inFooter && l.nofollow && l.isInternal).length;
      return n ? n + ' nofollow footer link(s)' : false;
    },
  }),
];

const anchorChecks: PageCheck[] = [
  pageCheck({
    id: 'internal-link-no-anchor-text', title: 'Has an internal link with no anchor text',
    category: 'links', severity: 'warning',
    why: 'A link with no text and no image alt passes no relevance signal and is unusable with a screen reader.',
    fix: 'Add anchor text, or alt text if the link wraps an image.',
    test: (p) => {
      const bad = p.links.filter((l) => l.isInternal && !l.anchor && !(l.wrapsImage && l.imageAlt));
      return bad.length ? bad.length + ' empty anchor(s)' : false;
    },
  }),
  pageCheck({
    id: 'outgoing-one-word-anchor', title: 'Page has outbound internal links with one word anchor',
    category: 'links', severity: 'notice',
    why: 'Single-word anchors carry limited topical signal about the destination.',
    fix: 'Use short descriptive phrases that state what the target page is about.',
    test: (p) => {
      const bad = p.links.filter((l) => l.isInternal && l.anchor && !l.anchor.includes(' '));
      return bad.length ? bad.length + ' one-word anchor(s)' : false;
    },
  }),
  pageCheck({
    id: 'outgoing-non-descriptive-anchor', title: 'Page has one or more outgoing followed links with non descriptive anchor text',
    category: 'links', severity: 'notice',
    why: 'Anchors like "click here" and "read more" describe the action rather than the destination, wasting the relevance signal and failing accessibility guidance.',
    fix: 'Replace with text naming the destination.',
    test: (p) => {
      const bad = p.links.filter((l) => !l.nofollow && isNonDescriptiveAnchor(l.anchor));
      return bad.length ? bad.length + ' generic anchor(s)' : false;
    },
  }),
  pageCheck({
    id: 'incoming-non-descriptive-anchor', title: 'Page has incoming followed links that do not use descriptive anchor text',
    category: 'links', severity: 'notice',
    why: 'Internal backlinks with generic anchors fail to tell search engines what this page is about.',
    fix: 'Update the anchor text on the linking pages.',
    test: (p, site) => {
      const bad = inboundOf(p, site).filter((l) => !l.nofollow && isNonDescriptiveAnchor(l.anchor));
      return bad.length ? bad.length + ' generic incoming anchor(s)' : false;
    },
  }),
  pageCheck({
    id: 'incoming-links-same-anchor', title: 'Page has internal backlinks with the same anchor',
    category: 'links', severity: 'notice',
    why: 'Every internal backlink using an identical anchor is a mild over-optimisation signal and forgoes ranking for related terms.',
    fix: 'Vary internal anchor text naturally across linking pages.',
    test: (p, site) => {
      const inbound = inboundOf(p, site).filter((l) => l.anchor);
      if (inbound.length < 3) return false;
      const anchors = new Set(inbound.map((l) => l.anchor.toLowerCase()));
      return anchors.size === 1 ? 'all ' + inbound.length + ' use "' + inbound[0]!.anchor + '"' : false;
    },
  }),
  pageCheck({
    id: 'anchored-image-no-alt', title: 'Page has an anchored image with no alt text',
    category: 'links', severity: 'warning',
    why: 'When a link wraps only an image, the alt text becomes the anchor text. Without it the link is silent to search engines and screen readers.',
    fix: 'Add alt text describing the link destination.',
    test: (p) => {
      const bad = p.links.filter((l) => l.wrapsImage && !l.anchor && !l.imageAlt);
      return bad.length ? bad.length + ' image link(s) without alt' : false;
    },
  }),
];

const targetChecks: PageCheck[] = [
  pageCheck({
    id: 'internal-links-to-4xx', title: 'Page has internal links to 4xx pages',
    category: 'links', severity: 'critical',
    why: 'Broken internal links waste crawl budget, dead-end users, and discard the equity sent to the missing page.',
    fix: 'Update or remove the link, or restore the target.',
    test: (p, site) => {
      const bad = p.links.filter((l) => {
        const s = targetStatus(site, l.href);
        return l.isInternal && s !== null && s >= 400 && s < 500;
      });
      return bad.length ? bad.length + ' link(s) to 4xx' : false;
    },
  }),
  pageCheck({
    id: 'internal-links-to-3xx', title: 'Page has internal links to 3xx pages',
    category: 'links', severity: 'warning',
    why: 'Linking through a redirect adds a hop for every crawl and every user, and slightly attenuates the equity passed.',
    fix: 'Link directly to the final destination URL.',
    test: (p, site) => {
      const bad = p.links.filter((l) => {
        const s = targetStatus(site, l.href);
        return l.isInternal && s !== null && s >= 300 && s < 400;
      });
      return bad.length ? bad.length + ' link(s) to 3xx' : false;
    },
  }),
  pageCheck({
    id: 'broken-links-to-external', title: 'Page has broken links to external websites',
    category: 'links', severity: 'warning',
    why: 'Dead outbound links are a poor user experience and signal unmaintained content.',
    fix: 'Update or remove the link.',
    test: (p, site) => {
      const bad = p.links.filter((l) => {
        const s = targetStatus(site, l.href);
        return l.isExternal && s !== null && s >= 400;
      });
      return bad.length ? bad.length + ' broken external link(s)' : false;
    },
  }),
  pageCheck({
    id: 'broken-jump-link', title: 'Broken jump link',
    category: 'links', severity: 'warning',
    why: 'A same-page anchor pointing at an id that does not exist silently does nothing when clicked.',
    fix: 'Add the missing id to the target element, or fix the fragment.',
    test: (p) => {
      const ids = new Set<string>();
      for (const m of p.html.matchAll(/\sid=["']([^"']+)["']/g)) ids.add(m[1]!);
      for (const m of p.html.matchAll(/\sname=["']([^"']+)["']/g)) ids.add(m[1]!);
      const bad = p.links.filter((l) =>
        l.isFragmentOnly && l.rawHref.length > 1 && !ids.has(decodeURIComponent(l.rawHref.slice(1))));
      return bad.length ? bad.length + ' broken fragment(s)' : false;
    },
  }),
  pageCheck({
    id: 'empty-href-attribute', title: 'Has a link with an empty href attribute',
    category: 'links', severity: 'warning',
    why: 'An empty href reloads the current page. It is usually a placeholder that was never filled in.',
    fix: 'Set a real destination, or use a <button> if the element triggers an action.',
    test: (p) => {
      const n = p.links.filter((l) => l.rawHref === '').length;
      return n ? n + ' empty href(s)' : false;
    },
  }),
  pageCheck({
    id: 'empty-links-hash', title: 'Empty links "#"',
    category: 'links', severity: 'notice',
    why: 'href="#" links are inert placeholders, commonly left behind on JavaScript-driven controls.',
    fix: 'Use <button> for actions, or provide a real href with progressive enhancement.',
    test: (p) => {
      const n = p.links.filter((l) => l.rawHref === '#').length;
      return n ? n + ' "#" link(s)' : false;
    },
  }),
  pageCheck({
    id: 'malformed-href-data', title: 'Page has outgoing links with malformed href data',
    category: 'links', severity: 'warning',
    why: 'An href that cannot be parsed as a URL will not be followed by any crawler.',
    fix: 'Correct the URL. Common causes are unencoded spaces and template variables that failed to interpolate.',
    test: (p) => {
      const bad = p.links.filter((l) =>
        l.rawHref && !l.href && !l.rawHref.startsWith('#')
        && !/^(javascript|mailto|tel|sms):/i.test(l.rawHref));
      return bad.length ? bad.length + ' malformed href(s)' : false;
    },
  }),
  pageCheck({
    id: 'link-whitespace-href', title: 'Has a link with whitespace in href attribute',
    category: 'links', severity: 'warning',
    why: 'Unencoded whitespace in a URL is handled inconsistently across crawlers and may resolve to the wrong target or not at all.',
    fix: 'Encode spaces as %20, or remove the stray whitespace.',
    test: (p) => {
      const n = p.links.filter((l) => /\s/.test(l.rawHref.trim()) && l.rawHref.trim() !== '').length;
      return n ? n + ' href(s) with whitespace' : false;
    },
  }),
  pageCheck({
    id: 'link-non-http-protocol', title: 'Page has link to a non-HTTP protocol',
    category: 'links', severity: 'notice',
    why: 'mailto, tel, ftp and similar links are not crawlable. Worth confirming they are intentional rather than the result of a broken template.',
    fix: 'No action needed if deliberate.',
    test: (p) => {
      const bad = p.links.filter((l) =>
        /^(ftp|mailto|tel|sms|file|news):/i.test(l.rawHref));
      return bad.length ? bad.length + ' non-HTTP link(s)' : false;
    },
  }),
  pageCheck({
    id: 'link-localhost', title: 'Has link with a URL referencing LocalHost or 127.0.0.1',
    category: 'internal', severity: 'critical',
    why: 'A localhost link is a development artefact shipped to production. It is broken for every visitor.',
    fix: 'Replace with the production URL. Usually a hardcoded base URL that should come from an environment variable.',
    test: (p) => {
      const n = p.links.filter((l) => /localhost|127\.0\.0\.1|0\.0\.0\.0/i.test(l.rawHref)).length;
      return n ? n + ' localhost link(s)' : false;
    },
  }),
  pageCheck({
    id: 'link-local-unc-path', title: 'Has link with a URL referencing a local or UNC file path',
    category: 'internal', severity: 'critical',
    why: 'file:// and UNC paths are inaccessible from a browser and expose internal infrastructure naming.',
    fix: 'Host the resource on the web server and link to it over HTTP.',
    test: (p) => {
      const n = p.links.filter((l) => /^(file:\/\/|\\\\|[a-z]:\\)/i.test(l.rawHref)).length;
      return n ? n + ' local path link(s)' : false;
    },
  }),
  pageCheck({
    id: 'link-url-in-onclick', title: 'Page has link with a URL in onclick attribute',
    category: 'links', severity: 'notice',
    why: 'Navigation implemented in onclick rather than href is not followed by crawlers, so the destination may never be discovered.',
    fix: 'Put the destination in href and enhance with JavaScript rather than replacing it.',
    test: (p) => {
      const n = p.links.filter((l) => l.onclick && /https?:|location|window\.open/i.test(l.onclick)).length;
      return n ? n + ' onclick navigation(s)' : false;
    },
  }),
  pageCheck({
    id: 'http-page-links-to-https', title: 'HTTP page has internal links to HTTPS',
    category: 'links', severity: 'notice',
    why: 'Mixed protocol linking within a site creates duplicate URL variants and inconsistent crawl paths.',
    fix: 'Serve everything over HTTPS and redirect HTTP to HTTPS site-wide.',
    test: (p) => {
      if (!p.finalUrl.startsWith('http://')) return false;
      const n = p.links.filter((l) => l.isInternal && l.href?.startsWith('https://')).length;
      return n ? n + ' HTTPS link(s) from an HTTP page' : false;
    },
  }),
];

const inboundChecks: PageCheck[] = [
  pageCheck({
    id: 'less-than-10-internal-backlinks', title: 'Page has less than 10 internal backlinks',
    category: 'links', severity: 'notice',
    why: 'Few internal backlinks means the page receives little link equity and reads as low priority within the site structure.',
    fix: 'Link to it from related content and relevant hub pages.',
    test: (p, site) => {
      const n = new Set(inboundOf(p, site).map((l) => l.fromUrl)).size;
      return n < K.minInternalBacklinks ? n + ' internal backlink(s)' : false;
    },
  }),
  pageCheck({
    id: 'only-nofollow-incoming-links', title: 'Page only has nofollow incoming internal links',
    category: 'links', severity: 'warning',
    why: 'Every internal link to this page is nofollowed, so it receives no equity at all and may be treated as unimportant.',
    fix: 'Remove nofollow from at least the primary internal links.',
    test: (p, site) => {
      const inbound = inboundOf(p, site);
      return inbound.length > 0 && inbound.every((l) => l.nofollow)
        ? 'all ' + inbound.length + ' incoming links are nofollow' : false;
    },
  }),
  pageCheck({
    id: 'follow-and-nofollow-incoming', title: 'URL receives both follow and nofollow internal links',
    category: 'links', severity: 'notice',
    why: 'Inconsistent rel attributes across links to the same target usually indicate an unintentional nofollow somewhere in a template.',
    fix: 'Make internal linking consistent — normally all followed.',
    test: (p, site) => {
      const inbound = inboundOf(p, site);
      const f = inbound.filter((l) => !l.nofollow).length;
      const nf = inbound.filter((l) => l.nofollow).length;
      return f > 0 && nf > 0 ? f + ' follow / ' + nf + ' nofollow' : false;
    },
  }),
  pageCheck({
    id: 'orphan-sitemap-only', title: 'Orphan URLs - only found via sitemap',
    category: 'links', severity: 'critical',
    why: 'The page is listed in the sitemap but nothing links to it. Crawlers reach it only via the sitemap, and it receives no internal link equity.',
    fix: 'Link to it from relevant pages within the site.',
    test: (p, site) => site.orphans.has(normalizeUrl(p.finalUrl)) && p.inSitemap,
  }),
  pageCheck({
    id: 'orphan-via-canonical', title: 'Orphan URLs – only found via canonical',
    category: 'links', severity: 'critical',
    why: 'The URL was discovered only because another page canonicalises to it. With no internal links it is effectively invisible in the site structure.',
    fix: 'Add internal links, or reconsider the canonical target.',
    test: (p, site) => {
      const key = normalizeUrl(p.finalUrl);
      if (!site.orphans.has(key) || p.inSitemap) return false;
      return site.pages.some((o) => o.canonical && normalizeUrl(o.canonical) === key
        && normalizeUrl(o.finalUrl) !== key);
    },
  }),
  pageCheck({
    id: 'orphan-via-redirect', title: 'Orphan URLs – only found via redirect',
    category: 'links', severity: 'critical',
    why: 'The only path to this URL is a redirect from elsewhere. Nothing links to it directly, so it accumulates no equity of its own.',
    fix: 'Link to the destination directly from relevant pages.',
    test: (p, site) => {
      const key = normalizeUrl(p.finalUrl);
      if (!site.orphans.has(key) || p.inSitemap) return false;
      return [...site.redirectTargets.values()].some((t) => normalizeUrl(t) === key);
    },
  }),
  pageCheck({
    id: 'orphan-isolated-cluster', title: 'Orphan URLs – only linked from other isolated URLs',
    category: 'links', severity: 'critical',
    why: 'The page is linked only from other orphans, forming an island disconnected from the main site graph. Equity never reaches the cluster.',
    fix: 'Link into the cluster from a well-connected hub page.',
    test: (p, site) => {
      const key = normalizeUrl(p.finalUrl);
      const inbound = site.inbound.get(key) ?? [];
      if (inbound.length === 0) return false;
      return inbound.every((l) => site.orphans.has(normalizeUrl(l.fromUrl)));
    },
  }),
];

export const LINK_CHECKS: PageCheck[] = [
  ...outgoingChecks, ...anchorChecks, ...targetChecks, ...inboundChecks,
];
